import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
// import any new fonts here
import { Geist, Geist_Mono, Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// create new font const
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'], // adjust as needed
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* add new font here follow same format */}
        <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}>
          
          {/* --- Your new Navbar component goes here --- */}
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}